"""Design tokens for the budget module (Finanmind reference UI)."""


class BudgetUiTheme:
    """Shared colors and layout hints; no behavior."""

    ACCENT = "#4f8ef7"
    ACCENT_HOVER = "#3d7de4"
    BG_MAIN = "#f5f6fa"
    BG_CARD = "#ffffff"
    BG_HOVER = "#f1f5f9"
    TXT_PRI = "#111827"
    TXT_SEC = "#6b7280"
    TXT_TER = "#9ca3af"
    BORDER = "#e5e7eb"
    RED = "#ef4444"
    GREEN = "#22c55e"
    AMBER = "#f59e0b"
    ICON_SALARY_BG = "#e8f0fe"
    BTN_ADD_LABEL_BG = "#dbeafe"
    BTN_ADD_LABEL_FG = "#1d4ed8"
    SIDEBAR_BG = "#181f2e"
    SIDEBAR_TXT = "#ffffff"
    SIDEBAR_MUTE = "#6b7a99"
    SIDEBAR_ACTIVE_BG = "#262f42"
    BADGE_OK_BG = "#dcfce7"
    BADGE_OK_FG = "#166534"
    BADGE_WARN_BG = "#fee2e2"
    BADGE_WARN_FG = "#dc2626"
    INFO_BG = "#eff6ff"
